version: "3"

services:
  php8:
    build:
      context: ./docker/php8
    container_name: ${PROJECT_NAME}-app
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - ./:/var/www/html/
      - ./docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
  nginx:
    platform: linux/x86_64
    image: nginx:1.26.0
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8
    networks:
      - app-network
  mysql:
    image: mysql:8.0.39
    container_name: ${PROJECT_NAME}-db
    ports:
      - "3306:3306"
    depends_on:
      - php8
    environment:
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      SERVICE_NAME: mysql
    networks:
      - app-network
  mysql_phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: "root"
      UPLOAD_LIMIT: 2048M
      MEMORY_LIMIT: 1024M
      MAX_EXECUTION_TIME: 3000
    networks:
      - app-network
  redis:
    image: redis:7.4.0
    container_name: ${PROJECT_NAME}-redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - /docker/redis:/data
    networks:
      - app-network
  redisui:
    image: patrikx3/p3x-redis-ui:2024.10.106
    container_name: ${PROJECT_NAME}-redisui
    ports:
      - "7843:7843"
    volumes:
      - /docker/p3x-redis-ui-settings:/settings
    networks:
      - app-network

networks:
  app-network:
    driver: bridge